import Navbar from "@/components/Navbar";
import TopBar from "@/components/TopBar";
import React from "react";
import Footer from "@/components/Footer";
import Map from "./components/Map";
import Contact from "./components/Contact";

type Props = {};

export const metadata = {
  title: "Kontakt - Eletronika samochodowa Uzarek - Chełm",
  description: "Generated by create next app",
};

const page = (props: Props) => {
  return (
    <div className="box-border w-full h-full overflow-x-hidden scroll-smooth">
      <TopBar />
      <Navbar />
      <Contact />
      <Map />
      <Footer />
    </div>
  );
};

export default page;
